- name: Cloning into gr-osmsdr
  git:
    repo: https://git.osmocom.org/gr-osmosdr
    dest: "{{working_dir}}/osmsdr"
# https://git.osmocom.org/gr-osmosdr
# https://github.com/csete/gr-osmosdr-gqrx

- name: Creates working directory
  file:
    path: "{{working_dir}}/osmsdr/build"
    state: directory

- name: Cmaking osmsdr
  command: chdir="{{working_dir}}/osmsdr/build" cmake ..

- make:
    chdir: "{{working_dir}}/osmsdr/build"
  become: yes

- make:
    chdir: "{{working_dir}}/osmsdr/build"
    target: install
  become: yes

- command: ldconfig
  args:
      chdir: "{{working_dir}}/osmsdr/build"
  become: yes
